module.exports = {
  PRIORITY: ['Critical', 'High', 'Medium', 'Low'],
  status: {
    Project: [{ key: -1, value: 'Rollback' }, { key: 0, value: 'New' }, { key: 1, value: 'Open' }, { key: 2, value: 'Finished' }, { key: 3, value: 'Closed' }],
    Issue: [{ key: -2, value: 'Rollback' }, { key: -1, value: 'Rejected' }, { key: 0, value: 'New' }, { key: 1, value: 'Approved' }, { key: 2, value: 'Solved' }, { key: 3, value: 'Closed' }],
    Request: [{ key: -2, value: 'Rollback' }, { key: -1, value: 'Rejected' }, { key: 0, value: 'New' }, { key: 1, value: 'Approved' }, { key: 2, value: 'Solved' }, { key: 3, value: 'Closed' }],
  },
  TYPE: ['Project', 'Issue', 'Request'],
  COLOR: {
    Create: 'green',
    Open: 'green',
    Comment: 'blue',
    Approve: 'green',
    Reject: 'red',
    Finish: 'green',
    Solve: 'green',
    Close: 'red',
    Rollback: 'red',
    Edit: 'green',
    Progress: 'blue',
  },
  ICON: {
    Create: 'plus-circle-o',
    Open: 'play-circle-o',
    Comment: 'info-circle-o',
    Approve: 'check-circle-o',
    Reject: 'close-circle-o',
    Finish: 'smile-o',
    Solve: 'smile-o',
    Close: 'copyright',
    Rollback: 'close-circle-o',
    Edit: 'edit',
    Progress: 'sync',
  },
  USERTYPE: ['OVT-EE', 'Non-OVT'],
  USERROLE: ['Default CC', 'Project Admin'],
}
