module.exports = [
  {
    id: 1,
    icon: 'switcher',
    name: 'Pending Task',
    router: '/pendingCase',
  },
  {
    id: 11,
    mpid: -1,
    bpid: 1,
    name: 'Task Info',
    router: '/caseInfo/:id',
  },
  {
    id: 12,
    mpid: -1,
    bpid: 1,
    name: 'Task Process',
    router: '/process/:id',
  },
  {
    id: 13,
    mpid: -1,
    bpid: 1,
    name: 'Task Issue',
    router: '/issues/:id',
  },
  {
    id: 14,
    mpid: -1,
    bpid: 1,
    name: 'Task Detail',
    router: '/case/:id',
  },
  {
    id: 15,
    mpid: -1,
    bpid: 1,
    name: 'Edit Issue',
    router: '/editIssue/:id',
  },
  {
    id: 2,
    name: 'New Project',
    icon: 'file-add',
    router: '/newProject',
  },
  {
    id: 3,
    name: 'New Issue/Request',
    icon: 'file-unknown',
    router: '/newIssue',
  },
  {
    id: 31,
    mpid: -1,
    bpid: 3,
    name: 'Issue Info',
    router: '/issue/:id',
  },
  {
    id: 4,
    name: 'Integrate Query',
    icon: 'search',
    router: '/query',
  },
  {
    id: 41,
    mpid: -1,
    bpid: 4,
    name: 'Issue Info',
    router: '/issueInfo/:id',
  },
  {
    id: 42,
    mpid: -1,
    bpid: 4,
    name: 'Project Info',
    router: '/projectInfo/:id',
  },
  {
    id: 5,
    name: 'Data Maintail Log',
    icon: 'anticon anticon-database',
    router: '/log',
  },
  {
    id: 6,
    name: 'User Management',
    icon: 'team',
    router: '/userManagement',
  },
  {
    id: 7,
    mpid: -1,
    name: 'User Info',
    router: '/userInfo',
  },
  // {
  //   id: 7,
  //   name: 'Role and Authority',
  //   icon: 'lock',
  // },
  // {
  //   id: 71,
  //   mpid: 7,
  //   bpid: 7,
  //   name: 'Role',
  //   icon: 'credit-card',
  //   router: '/admin/role',
  // },
  // {
  //   id: 72,
  //   mpid: 7,
  //   bpid: 7,
  //   name: 'List',
  //   icon: 'code-o',
  //   router: '/admin/list',
  // },
]
